### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by ettom** [leots/Arduino-PC-Monitor#5] opened 2018-05-21 21:52 UTC
Hey, I am having a problem getting your script to run. I'm running Python 3.4.0 and Open Hardware Monitor 0.7.1 Beta. OHM web server is running and accessible from the browser at localhost:8085.

```python
>python ArduinoPCMonitor.py
Only 1 port found: COM8. Connecting to it...
Traceback (most recent call last):
  File "ArduinoPCMonitor.py", line 234, in <module>
    main()
  File "ArduinoPCMonitor.py", line 197, in main
    config["gpu_mem_size"]
  File "ArduinoPCMonitor.py", line 129, in get_hardware_info
    temp_value = core_temp['Value'][:-5]
TypeError: 'int' object is not subscriptable

```
Contents of config.json
```
{
  "ohw_ip": "localhost",
  "ohw_port": "8085",
  "cpu_name": "AMD FX-6350",
  "gpu_name": "AMD Radeon HD 7800 Series",
  "gpu_mem_size": 2048
}
```

**Comment by leots** [comment] 2018-05-21 21:59
Hi,
This sounds similar to this issue: https://github.com/leots/Arduino-PC-Monitor/issues/4
I think the problem is that AMD CPUs have only 1 temperature sensor, and I didn't account for that in the program. Can you confirm that you see only 1 CPU temperature?

If that is the problem, I'll try to create an updated version which shows less temperatures if they aren't found, as soon as I have some time.

Thanks!

**Comment by ettom** [comment] 2018-05-21 22:03
Yes, I only see 1 CPU temp.

Screenshot:
https://i.imgur.com/g0FJEzl.png

I also don't see gpu memory size, so that must be the reason for the other error.
Thanks a lot!

**Comment by leots** [comment] 2018-05-23 07:59
I fixed the Python program, it should now run (tested with an FX-8320 which is similar, and an AMD GPU). It will display only 1 temperature for the CPU, and the voltage of the GPU core instead of the used memory.

However I'm not closing the issue because with less than 4 CPU temperature sensors, the Arduino still displays four "°C" symbols, just with no numbers next to them, so I still need to fix that.

**Comment by ettom** [comment] 2018-05-23 09:24
It works! Well, sort of.
![20180523_115845](https://user-images.githubusercontent.com/36895504/40414741-bf0ff256-5e81-11e8-9501-59ada5f80a6a.jpg)

I am using the LiquidCrystal_I2C and Wire libraries because I have an I2C lcd. It seems like the delimiters are not working. 
This is with 
```python 
arduino_str = \
      'C' + cpu + '|G'
```
![20180523_115753](https://user-images.githubusercontent.com/36895504/40415642-0fa5ecbe-5e84-11e8-87f0-4c8191ef83b9.jpg)

**Comment by leots** [comment] 2018-05-25 12:35
Hmm, this looks like the string sent to the Arduino by the Python program doesn't get split at all (you can see the "|" printed on the LCD). Did you make any changes here? https://github.com/leots/Arduino-PC-Monitor/blob/master/ArduinoPCMonitor.ino#L110-L114

For each part of the string, it goes to a specific part of the LCD and prints the values there, it doesn't print the entire string at once.

**Comment by ettom** [comment] 2018-05-25 21:06
The only changes i made were replacing the relevant lines with
```
#include <Wire.h> 
#include <LiquidCrystal_I2C.h>

LiquidCrystal_I2C lcd(0x27, 2, 1, 0, 4, 5, 6, 7, 3, POSITIVE);  // Set the LCD I2C address
```

**Comment by ghost** [comment] 2018-08-26 11:33
Hello.
I have the same problem as the topic starter:
```
Arduino-PC-Monitor-master\ArduinoPCMonitor.py 
Traceback (most recent call last):
  File "D:\Arduino-PC-Monitor-master\ArduinoPCMonitor.py", line 269, in <module>
    main()
  File "D:\Arduino-PC-Monitor-master\ArduinoPCMonitor.py", line 224, in main
    config['gpu_mem_size']
  File "D:\Arduino-PC-Monitor-master\ArduinoPCMonitor.py", line 124, in get_hardware_info
    cpu_temps = find_in_data(cpu_data, 'Temperatures')
  File "D:\Arduino-PC-Monitor-master\ArduinoPCMonitor.py", line 86, in find_in_data
    if ohw_data['Text'] == name:
TypeError: 'int' object is not subscriptable
```
Contents of config.json
```
  "ohw_ip": "localhost",
  "ohw_port": "8085",
  "cpu_name": "AMD FX(tm)-6100 Six-Core",
  "gpu_name": "NVIDIA GeForce GT 630",
  "gpu_mem_size": 4096
```
Screenshot:
[http://img.radiokot.ru/files/83148/medium/1o7c6cggh3.png](http://img.radiokot.ru/files/83148/medium/1o7c6cggh3.png)

I use:
- Open Hirdware monitor 0.7.1
- Python 3.7 + pyserial-3.4

**Comment by leots** [comment] 2018-08-26 11:43
Hmm, can you try using "AMD FX-6100" as your cpu_name in the config.json file? I think that's the problem.

**Comment by ghost** [comment] 2018-08-26 11:59
I changed the name of the CPU. The result is the same. It produces all the same errors.
I'm using the corrected code: [https://github.com/leots/Arduino-PC-Monitor/issues/6](https://github.com/leots/Arduino-PC-Monitor/issues/6)
I just tried to change the port. I also used unchanged (original) code. Arduino connected to the port number 1. Errors disappeared, but a message appeared:
```
Arduino-PC-Monitor-master\ArduinoPCMonitor (2).py 
Number of ports is not 1, can't connect!
```
Why can not I connect?

**Comment by leots** [comment] 2018-08-26 12:02
Can you post the full code you are running on pastebin for me to see? This message shouldn't appear if you used the updated main function from #6 as I removed it :\

**Comment by ghost** [comment] 2018-08-26 12:07
I use original code: [https://pastebin.com/F7LsNGCK](https://pastebin.com/F7LsNGCK)

**Comment by leots** [comment] 2018-08-26 12:24
Yes the code looks correct. Sorry I think I misread, the number of ports message is from the unchanged code. So the modified code connects to the Arduino, but there is another problem.

The int object error most likely means that the code is trying to find something that can't be found in your open hardware monitor data, but I don't know what. Can you go to http://localhost:8085/data.json on your browser, and post the contents in a pastebin? That will help me find what exactly is the problem.

Thanks!

**Comment by ghost** [comment] 2018-08-26 12:33
Thank you for your help. I myself can not solve this, because I do not understand python. Here are the data that the hardware monitor transmits: [https://pastebin.com/23V71cWq](https://pastebin.com/23V71cWq)

**Comment by ghost** [comment] 2018-08-27 14:59
Have you found the reason why the program does not work for me and gives errors?

**Comment by leots** [comment] 2018-08-27 15:27
Hi,

I've been travelling so I haven't had time yet. I will look into it tonight or tomorrow!

**Comment by ghost** [comment] 2018-08-27 15:28
Ok, Thank you!

**Comment by leots** [comment] 2018-08-27 18:30
I updated the code in the repo, now it should work for you without modifications. I added more detailed error messages (instead of int is not subscriptable) and now the Arduino serial port is set via the config.json file, so set it there!

If this works, I will close this issue as I don't have an I2C display to test (sorry @ettom...)

**Comment by leots** [comment] 2018-10-12 11:04
Assuming this is fixed, so I'm closing it...

**Closed as completed by leots** 2018-10-12 11:04 UTC
